### ISSUE TITLE
Exception while data loading

### ISSUE THREAD

**Issue by andrshamov** [farshadbayat/dynamic-mat-table-workspace#17]
Angular 10 

Exception on data loading:

core.js:4197 ERROR TypeError: this.dataSource.subscribe is not a function
    at DynamicMatTableComponent.ngAfterViewInit (dynamic-mat-table.js:3587)

What can be a reason?

**Comment by farshadbayat** [comment]
For some reason datasource just support BehaviorSubject from version 1.4.*. 
for example you can do this way:
`
dataSource = new BehaviorSubject([]); // new TableVirtualScrollDataSource([]);
`
and you can get data from BehaviorSubject in this way:
`
const firstRow = this.dataSource.value[0];
`

**Comment by mariannafld** [comment]
Farshad, thank you. 
 It is work now (@andrshamov opened an issue on my behave).
 However, another Exception is thrown:
core.js:4197 ERROR TypeError: Cannot read property 'checkViewportSize' of undefined
    at DynamicMatTableComponent.refreshUI (dynamic-mat-table.js:3551)
    
    As well, data in the table is not presented until click to any column header. 
    
Thank you in advance

**Comment by farshadbayat** [comment]
In the new version, the problem is solved and the document is updated.
Thanks for the refreshUI  💯
