### ISSUE TITLE
Add RouterLink for page navigation ?

### ISSUE THREAD

**Issue by suriyaJaay** [farshadbayat/dynamic-mat-table-workspace#19]
Could you pls tell me how to add router navigation on clicking table cell value?

Thanks

**Comment by farshadbayat** [comment]
Here you are:
HTML:
```
 <dynamic-mat-table
(onRowEvent)="rowTable_onEvent($event)"
</dynamic-mat-table>
```
TS:

```
rowTable_onEvent(e: IRowEvent) { 
    console.log(e.event);
           
    if(e.event === 'ButtonClick' ) {

    } else if(e.event === 'CellClick' ) {

    }
  }
```
All Event on Row:
export declare type RowEventType = 'MasterSelectionChange' | 'RowSelectionChange' | 'RowActionMenu' | 'RowClick' | 'CellClick' | 'BeforContextMenuOpen' | 'ContextMenuClick';
