### ISSUE TITLE
pagination doesn't work as expected.

### ISSUE THREAD

**Issue by sonu-suresh** [farshadbayat/dynamic-mat-table-workspace#36]
https://stackblitz.com/edit/angular-ivy-z9ssa8?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fsimple-table%2Fsimple-table.component.html,src%2Fapp%2Fsimple-table%2Fsimple-table.component.css,src%2Fapp%2Fsimple-table%2Fsimple-table.config.ts

I have created this stackblitz where I have added 25 rows to the table, but pagination is not working. 

Please guide me if I made any mistake in setting it up, or it's a bug?

**Comment by farshadbayat** [comment]
I create example for you.

**Comment by farshadbayat** [comment]
FIX @ dynamic-mat-table@1.5.7.
